syntax = "proto3";

package syralon.errors;

import "google/protobuf/descriptor.proto";

option go_package = "github.com/syralon/protoc-gen-go/proto/syralon/errors;errors";

extend google.protobuf.EnumOptions {
  bool as_error = 36846;
  ErrorOption default_error = 36847;
}

extend google.protobuf.EnumValueOptions {
  ErrorOption error = 36848;
}

message ErrorOption {
  optional string message = 1;
  optional string reason = 2;
  optional int32 status = 3;
}

message Error {
  int32 code = 1;
  string message = 2;
  string reason = 3;
  int32 status_code = 4;
}
