// Code generated by protoc-gen-choco-errors. DO NOT EDIT.
package http

import "fmt"

import errorspb "github.com/syralon/protoc-gen-go/proto/syralon/errors"

var STATUS_messages = map[STATUS]string{
	STATUS_UNSPECIFIED:                     "Unknown Error",
	STATUS_CONTINUE:                        "Continue",
	STATUS_SWITCHING_PROTOCOLS:             "Switching Protocols",
	STATUS_PROCESSING:                      "Processing",
	STATUS_EARLY_HINTS:                     "Early Hints",
	STATUS_OK:                              "Ok",
	STATUS_CREATED:                         "Created",
	STATUS_ACCEPTED:                        "Accepted",
	STATUS_NON_AUTHORITATIVE_INFO:          "Non Authoritative Info",
	STATUS_NO_CONTENT:                      "No Content",
	STATUS_RESET_CONTENT:                   "Reset Content",
	STATUS_PARTIAL_CONTENT:                 "Partial Content",
	STATUS_MULTI_STATUS:                    "Multi Status",
	STATUS_ALREADY_REPORTED:                "Already Reported",
	STATUS_IMUSED:                          "Imused",
	STATUS_MULTIPLE_CHOICES:                "Multiple Choices",
	STATUS_MOVED_PERMANENTLY:               "Moved Permanently",
	STATUS_FOUND:                           "Found",
	STATUS_SEE_OTHER:                       "See Other",
	STATUS_NOT_MODIFIED:                    "Not Modified",
	STATUS_USE_PROXY:                       "Use Proxy",
	STATUS_TEMPORARY_REDIRECT:              "Temporary Redirect",
	STATUS_PERMANENT_REDIRECT:              "Permanent Redirect",
	STATUS_BAD_REQUEST:                     "Bad Request",
	STATUS_UNAUTHORIZED:                    "Unauthorized",
	STATUS_PAYMENT_REQUIRED:                "Payment Required",
	STATUS_FORBIDDEN:                       "Forbidden",
	STATUS_NOT_FOUND:                       "Not Found",
	STATUS_METHOD_NOT_ALLOWED:              "Method Not Allowed",
	STATUS_NOT_ACCEPTABLE:                  "Not Acceptable",
	STATUS_PROXY_AUTH_REQUIRED:             "Proxy Auth Required",
	STATUS_REQUEST_TIMEOUT:                 "Request Timeout",
	STATUS_CONFLICT:                        "Conflict",
	STATUS_GONE:                            "Gone",
	STATUS_LENGTH_REQUIRED:                 "Length Required",
	STATUS_PRECONDITION_FAILED:             "Precondition Failed",
	STATUS_REQUEST_ENTITY_TOO_LARGE:        "Request Entity Too Large",
	STATUS_REQUEST_URITOO_LONG:             "Request Uritoo Long",
	STATUS_UNSUPPORTED_MEDIA_TYPE:          "Unsupported Media Type",
	STATUS_REQUESTED_RANGE_NOT_SATISFIABLE: "Requested Range Not Satisfiable",
	STATUS_EXPECTATION_FAILED:              "Expectation Failed",
	STATUS_TEAPOT:                          "Teapot",
	STATUS_MISDIRECTED_REQUEST:             "Misdirected Request",
	STATUS_UNPROCESSABLE_ENTITY:            "Unprocessable Entity",
	STATUS_LOCKED:                          "Locked",
	STATUS_FAILED_DEPENDENCY:               "Failed Dependency",
	STATUS_TOO_EARLY:                       "Too Early",
	STATUS_UPGRADE_REQUIRED:                "Upgrade Required",
	STATUS_PRECONDITION_REQUIRED:           "Precondition Required",
	STATUS_TOO_MANY_REQUESTS:               "Too Many Requests",
	STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE: "Request Header Fields Too Large",
	STATUS_UNAVAILABLE_FOR_LEGAL_REASONS:   "Unavailable For Legal Reasons",
	STATUS_INTERNAL_SERVER_ERROR:           "Internal Server Error",
	STATUS_NOT_IMPLEMENTED:                 "Not Implemented",
	STATUS_BAD_GATEWAY:                     "Bad Gateway",
	STATUS_SERVICE_UNAVAILABLE:             "Service Unavailable",
	STATUS_GATEWAY_TIMEOUT:                 "Gateway Timeout",
	STATUS_HTTPVERSION_NOT_SUPPORTED:       "Httpversion Not Supported",
	STATUS_VARIANT_ALSO_NEGOTIATES:         "Variant Also Negotiates",
	STATUS_INSUFFICIENT_STORAGE:            "Insufficient Storage",
	STATUS_LOOP_DETECTED:                   "Loop Detected",
	STATUS_NOT_EXTENDED:                    "Not Extended",
	STATUS_NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
}

func (e STATUS) Message() string {
	return STATUS_messages[e]
}

var STATUS_statuses = map[STATUS]int32{
	STATUS_UNSPECIFIED:                     500,
	STATUS_CONTINUE:                        100,
	STATUS_SWITCHING_PROTOCOLS:             101,
	STATUS_PROCESSING:                      102,
	STATUS_EARLY_HINTS:                     103,
	STATUS_OK:                              200,
	STATUS_CREATED:                         201,
	STATUS_ACCEPTED:                        202,
	STATUS_NON_AUTHORITATIVE_INFO:          203,
	STATUS_NO_CONTENT:                      204,
	STATUS_RESET_CONTENT:                   205,
	STATUS_PARTIAL_CONTENT:                 206,
	STATUS_MULTI_STATUS:                    207,
	STATUS_ALREADY_REPORTED:                208,
	STATUS_IMUSED:                          226,
	STATUS_MULTIPLE_CHOICES:                300,
	STATUS_MOVED_PERMANENTLY:               301,
	STATUS_FOUND:                           302,
	STATUS_SEE_OTHER:                       303,
	STATUS_NOT_MODIFIED:                    304,
	STATUS_USE_PROXY:                       305,
	STATUS_TEMPORARY_REDIRECT:              307,
	STATUS_PERMANENT_REDIRECT:              308,
	STATUS_BAD_REQUEST:                     400,
	STATUS_UNAUTHORIZED:                    401,
	STATUS_PAYMENT_REQUIRED:                402,
	STATUS_FORBIDDEN:                       403,
	STATUS_NOT_FOUND:                       404,
	STATUS_METHOD_NOT_ALLOWED:              405,
	STATUS_NOT_ACCEPTABLE:                  406,
	STATUS_PROXY_AUTH_REQUIRED:             407,
	STATUS_REQUEST_TIMEOUT:                 408,
	STATUS_CONFLICT:                        409,
	STATUS_GONE:                            410,
	STATUS_LENGTH_REQUIRED:                 411,
	STATUS_PRECONDITION_FAILED:             412,
	STATUS_REQUEST_ENTITY_TOO_LARGE:        413,
	STATUS_REQUEST_URITOO_LONG:             414,
	STATUS_UNSUPPORTED_MEDIA_TYPE:          415,
	STATUS_REQUESTED_RANGE_NOT_SATISFIABLE: 416,
	STATUS_EXPECTATION_FAILED:              417,
	STATUS_TEAPOT:                          418,
	STATUS_MISDIRECTED_REQUEST:             421,
	STATUS_UNPROCESSABLE_ENTITY:            422,
	STATUS_LOCKED:                          423,
	STATUS_FAILED_DEPENDENCY:               424,
	STATUS_TOO_EARLY:                       425,
	STATUS_UPGRADE_REQUIRED:                426,
	STATUS_PRECONDITION_REQUIRED:           428,
	STATUS_TOO_MANY_REQUESTS:               429,
	STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
	STATUS_UNAVAILABLE_FOR_LEGAL_REASONS:   451,
	STATUS_INTERNAL_SERVER_ERROR:           500,
	STATUS_NOT_IMPLEMENTED:                 501,
	STATUS_BAD_GATEWAY:                     502,
	STATUS_SERVICE_UNAVAILABLE:             503,
	STATUS_GATEWAY_TIMEOUT:                 504,
	STATUS_HTTPVERSION_NOT_SUPPORTED:       505,
	STATUS_VARIANT_ALSO_NEGOTIATES:         506,
	STATUS_INSUFFICIENT_STORAGE:            507,
	STATUS_LOOP_DETECTED:                   508,
	STATUS_NOT_EXTENDED:                    510,
	STATUS_NETWORK_AUTHENTICATION_REQUIRED: 511,
}

func (e STATUS) Status() int32 {
	return STATUS_statuses[e]
}

// Error
// implemented error interface
func (e STATUS) Error() string {
	return fmt.Sprintf("%d: %s", e, STATUS_messages[e])
}

// ToError
// convert to *errorspb.Error
func (e STATUS) ToError() *errorspb.Error {
	if _, ok := STATUS_name[int32(e)]; ok {
		return &errorspb.Error{
			Message:    STATUS_messages[e],
			Code:       int32(e),
			StatusCode: STATUS_statuses[e],
		}
	}
	return errorspb.New(errorspb.CodeUnknown, "unknown error")
}

// Unwrap
// unwrap error
func (e STATUS) Unwrap() error { return e.ToError() }
